version: 2.1
workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "Building..."

  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "Running tests..."
